### ISSUE TITLE
Support Java Modules

### ISSUE THREAD

**Issue by aalmiray** [ethlo/itu#14]
`v1.7.2` defines an automatic module name

```
$ jarviz module name --gav com.ethlo.time:itu:1.7.0
subject: itu-1.7.0.jar
name: itu
source: filename
automatic: true
valid: true

$ jarviz module descriptor --gav com.ethlo.time:itu:1.7.0
subject: itu-1.7.0.jar
name: itu
version: 1.7.0
open: false
automatic: true
requires:
  java.base mandated
contains:
  com.ethlo.time
  com.ethlo.time.internal

$ jarviz bytecode show --gav com.ethlo.time:itu:1.7.0
subject: itu-1.7.0.jar
Unversioned classes. Bytecode version: 52 (Java 8) total: 18
```

I'd be great if the library supplied a full Java module descriptor. It's possible to keep bytecode baseline compatible with Java 8 while providing a full module descriptor thanks to [ModiTect](https://github.com/moditect/moditect). This will help modular projects that consume this library, specifically those that create custom Java Runtimes with `jlink`, as the latter does not support automatic modules but explicit modules. If interested I can send a PR to make it happen.

**Comment by ethlo** [comment]
Hi! Thanks for your request.
This is not something I have any experience with. Do you need the descriptor added and also a version that is Java 8 bytecode compatible?

**Comment by aalmiray** [comment]
Yes, exactly. Both conditions are required. Here's how the PR could look like https://github.com/networknt/json-schema-validator/pull/728

Btw, I could also prepare a GH workfklow for build/test.

**Comment by ethlo** [comment]
Yes, both options sounds like an improvement to me, thank you!
