### ISSUE TITLE
Support OSGI

### ISSUE THREAD

**Issue by marcoSpoethAtYatta** [ethlo/itu#16]
Greetings,
I am currently trying to use [JSON-Schema-Validator](https://github.com/networknt/json-schema-validator) in our project that uses OSGI. JSON-Schema-Validator is already OSGI-ready, but it has since started using your ITU as a dependency, which prevents the validator from working in OSGI projects.

Would you be so kind to adapt ITU to an OSGI-bundle? The process should be fairly straightforward and would only require you to add a few lines of text to the pom.xml file. These changes wouldn't affect most people, but would help those using OSGI immensly.

You can reference JSON-Schema-Validator's POM.xml. I've highlighted the required lines for the Maven plugin [here](https://github.com/networknt/json-schema-validator/blob/master/pom.xml#L184). Additionally [this single line](https://github.com/networknt/json-schema-validator/blob/master/pom.xml#L27) to set the packaging as a 'bundle'. ITU will be fully OSGI compliant with the Maven plugin and the packaging declaration added.

A more detailed guide can be found [here](https://bnd.bndtools.org/tools/felix-maven.html).

If you'd like, I can make these changes myself as a PR for you to check out.

**Comment by ethlo** [comment]
Hi! OSGI; that was a blast from the past for me. I can include support. I have no working knowledge of OSGI, so if you prepare a PR, that would be much appreciated!  Thank you.

**Comment by marcoSpoethAtYatta** [comment]
Thank you for your swift response! I forked the repo and made a PR for the pom.xml changes. I tested the resulting jar in a local OSGI project and everything was working.

[Link to the PR](https://github.com/ethlo/itu/pull/17)

**Comment by ethlo** [comment]
Thank you! Released in version 1.7.3
